- name: db
  hosts: host02
  become: yes

  tasks:
    - name: Install packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3
          - pip
          - ufw
        state: latest
      become: true

    - name: Copy postgresql.conf
      template:
        src: ./postgresql.conf
        dest: "/etc/postgresql/15/main/postgresql.conf"

    - name: Copy pg_hba.conf
      template:
        src: ./pg_hba.conf
        dest: "/etc/postgresql/15/main/pg_hba.conf"

    - name: Allow PostgreSQL through UFW
      ufw:
        rule: allow
        port: 5432
        proto: tcp

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started

    - name: Install Python packages
      pip:
        name:
          - psycopg2-binary
        extra_args: --break-system-packages

    - name: Create replication user 'repl_user'
      become: true
      become_user: postgres
      postgresql_user:
        name: repl_user
        password: 123
        role_attr_flags: REPLICATION

    - name: Create database tg_bot
      become_user: postgres
      postgresql_db:
        name: tg_bot
        state: present

    - name: Create tables phone_numbers and emails
      become_user: postgres
      postgresql_query:
        db: tg_bot
        query: |
          CREATE TABLE IF NOT EXISTS phone_numbers(
              id SERIAL PRIMARY KEY,
              phone_number varchar(20)
          );
          CREATE TABLE IF NOT EXISTS emails(
              id SERIAL PRIMARY KEY,
              email varchar(255)
          );
          ALTER USER postgres WITH PASSWORD '123';
    - name: UMASK PostgreSQL logs
      file:
        path: /var/log/postgresql/postgresql-15-main.log
        mode: '0777'
        state: touch

- name: db_repl
  hosts: host03
  become: yes

  tasks:
    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3
          - pip
          - ufw
        state: latest
      become: true

    - name: Copy postgresql.conf
      template:
        src: ./postgresql_repl.conf
        dest: "/etc/postgresql/15/main/postgresql.conf"

    - name: Allow PostgreSQL through UFW
      ufw:
        rule: allow
        port: 5432
        proto: tcp

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started

    - name: Install Python packages
      pip:
        name:
          - psycopg2-binary
        extra_args: --break-system-packages

    - name: Change postgres password
      shell: "echo 'postgres:123' | chpasswd"

    - name: Stop PostgreSQL service
      service:
        name: postgresql
        state: stopped

    - name: Remove existing PostgreSQL data directory
      file:
        path: /var/lib/postgresql/15/main
        state: absent

    - name: Create PostgreSQL data directory
      file:
        path: /var/lib/postgresql/15/main
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Create base backup
      become_user: postgres
      command: pg_basebackup -h 192.168.58.167 -U repl_user -D "/var/lib/postgresql/15/main" -P
      environment:
        PGPASSWORD: "123"

    - name: Change permissions on PostgreSQL data directory
      file:
        path: /var/lib/postgresql/15/main
        state: directory
        recurse: yes
        mode: '0777'

    - name: Start PostgreSQL service after backup
      service:
        name: postgresql
        state: started

- name: bot
  hosts: host01
  become: yes

  tasks:

  - name: Install packages
    apt:
      name:
        - python3.11-venv
        - python3
        - pip
        - ufw
      state: latest

  - name: Allow PostgreSQL through UFW
    ufw:
      rule: allow
      port: 5432
      proto: tcp

  - name: Create Groups
    group:
      name: "{{item}}"
      state: present
    loop:
      - dev
      - test

  - name: Create User
    user:
      name: "{{item.client_name}}"
      shell: /bin/bash/
      groups: test
      append: yes
      home: "/home/{{item.home_dir}}"
    with_items:
      - {client_name: test, home_dir: home_dir_test}

  - name: Git Clone the repository
    git:
      repo: https://github.com/Rd1v1/devops_bot.git
      dest: /devops_bot
      version: docker
      force: yes

  - name: Install Python packages
    pip:
      requirements: /devops_bot/bot/requirements.txt
      extra_args: --break-system-packages
      virtualenv: /devops_bot/.venv
      virtualenv_command: /usr/bin/python3.11 -m venv

  - name: Copy .env file
    template:
      src: ./.env
      dest: /devops_bot/bot/.env

  - name: bot launch
    shell: |
        python3 /devops_bot/bot/main.py
