
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                trust
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             0.0.0.0/0               md5
# IPv6 local connections:
host    all             all             ::/0                    md5

#host    replication     all             db_repl/32              md5
host    all             all             172.18.0.1/24           md5
host    all             all             172.18.0.2/24           md5
host    all             all             172.18.0.3/24           md5
host    all             all             172.18.0.4/24           md5
host    replication     repl_user       172.18.0.1/24           md5
host    replication     repl_user       172.18.0.2/24           md5
host    replication     repl_user       172.18.0.3/24           md5
host    replication     repl_user       172.18.0.4/24           md5